### ISSUE TITLE
SBT ResolveException when dowloading

### ISSUE THREAD

**Issue by peacefulotter** [tototoshi/play-json-generic#2]
## Details:
Windows 10
Scala 2.13.10
SBT 1.7.2
Java 11.0.6

## Issue
throws `sbt.librarymanagement.ResolveException: Error downloading com.github.tototoshi:play-json-generic_2.13:0.1.1`
on 
```sbt
libraryDependencies += "com.github.tototoshi" %% "play-json-generic" % "0.1.1"
```

From what I have seen, sbt looks for the following pom: 
https://repo1.maven.org/maven2/com/github/tototoshi/play-json-generic_2.13/0.1.1/play-json-generic_2.13-0.1.1.pom

But this link does not exist - I think `play-json-generic_2.13`  in the URL should be replaced by `play-json-generic_2.12`

Overall, I think the correct link should be: 
https://repo1.maven.org/maven2/com/github/tototoshi/play-json-generic_2.12/0.1.2/play-json-generic_2.12-0.1.2.pom

Thanks for your help

**Comment by tototoshi** [comment]
Hi. This library is a little old and not built with scala 2.13.
Now this is not actively maintained but I will publish for scala 2.13 when I have time.
